runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /(.*)/
  static_files: \1/index.html
  upload: .*/index\.html

- url: /js
  static_dir: js

- url: /about
  static_dir: about

- url: /css
  static_dir: css

- url: /categories
  static_dir: categories

- url: /contact
  static_dir: contact

- url: /post
  static_dir: post

- url: /tags
  static_dir: tags

- url: /gallery
  static_dir: gallery

- url: /images
  static_dir: images

- url: /plugins
  static_dir: plugins

- url: /portfolio
  static_dir: portfolio

- url: /codeofconduct
  static_files: post/code-of-conduct/index.html
  upload: post/code-of-conduct/index.html

- url: /.*
  script: backend.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
  - remote_api: on
