baseURL = "/"
languageCode = "en-uk"
title = "Sydney Open Research Network"
theme = "timer-hugo"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about/"
        weight  = 2
    [[menu.nav]]
        name    = "Code of Conduct"
        url     = "/codeofconduct/"
        weight  = 3
    [[menu.nav]]
        name    = "Posts"
        url     = "/post/"
        weight  = 4
    #[[menu.nav]]
    #    name    = "Contact"
    #    url     = "/contact"
    #    weight  = 4

# Site Params
[params]
    home = "Home"
    logo = "images/sos-bw-small.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/bg.jpg"
        heading = "WELCOME TO THE SYDNEY OPEN RESEARCH NETWORK"
        description = "A hub for Open Research practitioners in Sydney, Australia."
        #btn     = true
        #btnText = "Download More"
        #btnURL  = "https://themefisher.com/"
        [[params.banner.flipText]]
            title   = "OPEN SCIENCE"
        [[params.banner.flipText]]
            title   = "OPEN ACCESS"
        [[params.banner.flipText]]
            title   = "OPEN HUMANITIES"
        [[params.banner.flipText]]
            title   = "OPEN EDUCATION"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT SYDNEY OPEN RESEARCH"
        content = "Open science and open research practices are growing in Australia, but discovering open research can feel like an isolating experience. This is a mechanism to promote open science and open practices in New South Wales, to build a sense of community amongst people who might otherwise feel like the only open researchers they know. <br>We aim to help you find like-minded folks, support efforts to reform institutional policies and practices, and educate others about open research. Follow us on <a href='https://twitter.com/SydneyOpenRes'>twitter</a> for updates. Sydney Open Research is an inclusive and welcoming community by design. To preserve this, our activities are subject to our <a href='codeofconduct'>Code of Conduct</a>. Please familiarise yourself with it."
        image   = "images/about/sos3.png"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "OPEN RESEARCH COMMUNITIES IN SYDNEY"
        subtitle= "Want to find some friendly open science people near you? Check out some of the communities, research groups, and events in the Sydney region!"
